namespace CrediPrest.Application.DTOs.Clients;

public sealed record ClientDto(
    Guid Id,
    string FullName,
    string IdentificationNumber,
    string Phone,
    string Address,
    string? Email,
    string? PersonalReference1,
    string? ReferencePhone1,
    string? PersonalReference2,
    string? ReferencePhone2,
    string? BacAccountNumber,
    string? LafiseAccountNumber,
    string? BamproAccountNumber,
    string PreferredPaymentMethod,
    bool HasKash,
    string? KashAccount,
    string? Notes,
    bool IsActive,
    DateTime RegisteredAtUtc,
    int ActiveLoans,
    decimal PendingCordobas,
    decimal PendingUsd);

public sealed record CreateClientRequest(
    string FullName,
    string IdentificationNumber,
    string Phone,
    string Address,
    string? Email,
    string? PersonalReference1,
    string? ReferencePhone1,
    string? PersonalReference2,
    string? ReferencePhone2,
    string? BacAccountNumber,
    string? LafiseAccountNumber,
    string? BamproAccountNumber,
    string? PreferredPaymentMethod,
    bool HasKash,
    string? KashAccount,
    string? Notes);

public sealed record UpdateClientRequest(
    string FullName,
    string IdentificationNumber,
    string Phone,
    string Address,
    string? Email,
    string? PersonalReference1,
    string? ReferencePhone1,
    string? PersonalReference2,
    string? ReferencePhone2,
    string? BacAccountNumber,
    string? LafiseAccountNumber,
    string? BamproAccountNumber,
    string? PreferredPaymentMethod,
    bool HasKash,
    string? KashAccount,
    string? Notes,
    bool IsActive);
